name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: starter/backend

      - name: Run lint
        run: |
          pipenv run lint
        working-directory: starter/backend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: starter/backend

      - name: Run tests
        run: |
          pipenv run test
        working-directory: starter/backend

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Validate AWS CLI credentials
        run: aws sts get-caller-identity

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private
          registries: 418941673572

      - name: Build Docker image
        run: |
          docker build -t 418941673572.dkr.ecr.us-east-1.amazonaws.com/backend:latest .
        working-directory: starter/backend

      - name: Push Docker image to ECR
        run: |
          docker push 418941673572.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name cluster || { echo "Failed to update kubeconfig"; exit 1; }
          kubectl config current-context
          kubectl get nodes || { echo "Failed to get nodes"; exit 1; }

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend backend=418941673572.dkr.ecr.us-east-1.amazonaws.com/backend:latest || { echo "Failed to set image"; exit 1; }
          kubectl rollout status deployment/backend || { echo "Failed to rollout status"; exit 1; }
