name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: starter/frontend

      - name: Run lint
        run: npm run lint
        working-directory: starter/frontend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: starter/frontend

      - name: Run tests
        run: npm run test
        working-directory: starter/frontend

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private
          registries: 418941673572

      - name: Build Docker image
        run: |
          docker build --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.REACT_APP_MOVIE_API_URL }} \
          -t 418941673572.dkr.ecr.us-east-1.amazonaws.com/frontend:latest \
          .
        working-directory: starter/frontend

      - name: Push Docker image to ECR
        run: |
          docker push 418941673572.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name cluster || { echo "Failed to update kubeconfig"; exit 1; }
          kubectl config view || { echo "Failed to view kubeconfig"; exit 1; }
          kubectl get nodes || { echo "Failed to get nodes"; exit 1; }

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/frontend frontend=418941673572.dkr.ecr.us-east-1.amazonaws.com/frontend:latest || { echo "Failed to set image"; exit 1; }
          kubectl rollout status deployment/frontend || { echo "Failed to rollout status"; exit 1; }
